config/routes.rb
Rails.application.routes.draw do
  resources :departamentos
  resources :produtos, only: [:new, :create, :destroy, :edit, :update]
  get "/produtos/busca" => "produtos#busca", as: :busca_produto
  root "produtos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/departamento.rb
class Departamento < ApplicationRecord
end

app/models/produto.rb
class Produto < ApplicationRecord

	belongs_to :departamento

	validates :quantidade, presence: true 
	validates :preco, presence: true 
	validates :descricao, presence: true 
	validates :nome, length: { minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController
  before_action :set_departamento, only: %i[ show edit update destroy ]

  # GET /departamentos or /departamentos.json
  def index
    @departamentos = Departamento.all
  end

  # GET /departamentos/1 or /departamentos/1.json
  def show
  end

  # GET /departamentos/new
  def new
    @departamento = Departamento.new
  end

  # GET /departamentos/1/edit
  def edit
  end

  # POST /departamentos or /departamentos.json
  def create
    @departamento = Departamento.new(departamento_params)

    respond_to do |format|
      if @departamento.save
        format.html { redirect_to @departamento, notice: "Departamento was successfully created." }
        format.json { render :show, status: :created, location: @departamento }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departamentos/1 or /departamentos/1.json
  def update
    respond_to do |format|
      if @departamento.update(departamento_params)
        format.html { redirect_to @departamento, notice: "Departamento was successfully updated." }
        format.json { render :show, status: :ok, location: @departamento }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departamentos/1 or /departamentos/1.json
  def destroy
    @departamento.destroy
    respond_to do |format|
      format.html { redirect_to departamentos_url, notice: "Departamento was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_departamento
      @departamento = Departamento.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def departamento_params
      params.require(:departamento).permit(:nome)
    end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: %i[edit update destroy]

  def index
    @produtos_por_nome = Produto.all.order(:nome).limit 5
    @produtos_por_preco = Produto.all.order(:preco).limit 2
    @produtos_por_descricao = Produto.all.order(:descricao).limit 3
  end

  def create
    produto_params
    nome = params['nome']
    descricao = params['descricao']
    quantidade = params['quantidade']
    preco = params['preco']
    valores = produto_params
    @produto = Produto.new valores
    if @produto.save
      flash[:notice] = 'Produto salvo' # flash dura mais de uma requisição na Web#
      redirect_to root_url
    else
      renderiza :new
    end
    # produto = Produto.create valores#
  end

  def edit
    renderiza :edit
  end

  def update
    produto_params
    valores = produto_params
    if @produto.update valores
      flash[:notice] = 'Produto Atualizado com Sucesso'
      redirect_to root_url
    else
      renderiza :edit
    end
  end

  def new
    @produto = Produto.new
    renderiza :new
  end

  def busca
    @buscar_nome = params[:nome]
    @produtos = Produto.where 'nome like ?', "%#{@buscar_nome}%"
  end

  def destroy
    if @produto.destroy
      flash[:notice1] = 'Produto Excluido'
      redirect_to root_url
    else
      redirect_to root_url
    end
  end

  private

  def renderiza(view)
    @departamentos = Departamento.all
    render view
  end

  def set_produto
    id = params[:id]
    @produto = Produto.find(id)
  end

  def produto_params
    params.require(:produto).permit :nome, :descricao, :quantidade, :preco, :departamento_id
  end
end

%( Aqui onde fazemos as mudanças em nosso controller, que antes estava no nosso HTML, agora nossa lógica está aqui e o HTML realmente no HTML views )

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/departamentos/_form.html.erb
<%= form_with(model: departamento) do |form| %>
  <% if departamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(departamento.errors.count, "error") %> prohibited this departamento from being saved:</h2>

      <ul>
        <% departamento.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/departamentos/edit.html.erb
<h1>Editing Departamento</h1>

<%= render 'form', departamento: @departamento %>

<%= link_to 'Show', @departamento %> |
<%= link_to 'Back', departamentos_path %>

app/views/departamentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Departamentos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departamentos.each do |departamento| %>
      <tr>
        <td><%= departamento.nome %></td>
        <td><%= link_to 'Show', departamento %></td>
        <td><%= link_to 'Edit', edit_departamento_path(departamento) %></td>
        <td><%= link_to 'Destroy', departamento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Departamento', new_departamento_path %>

app/views/departamentos/new.html.erb
<h1>New Departamento</h1>

<%= render 'form', departamento: @departamento %>

<%= link_to 'Back', departamentos_path %>

app/views/departamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @departamento.nome %>
</p>

<%= link_to 'Edit', edit_departamento_path(@departamento) %> |
<%= link_to 'Back', departamentos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lojadecamisetas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= nav_bar brand: "Alisson", brand_link: root_url do %>
      <%= form_tag busca_produto_path,
                                  method: :get,
                                  class: "navbar-form navbar-right" do %>
        <div class="form-group">
          <%= text_field_tag :nome, @buscar_nome , class: "form-control" %>
          <%= button_to "Buscar", nil, class: "btn btn-primary" %>
        </div>
      <% end %>
    <% end %>
    <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/produtos/_forms.html.erb
<% @produto.errors.full_messages.each do |message| %>
	<div class="alert alert-danger" role= "alert"><%= message %></div>
<% end %>

	<%= form_for @produto do |f|%> <!--Atualiza os dados de um modelo ou cria!-->

	<form action="/produto" method="post"> <!--ação para mandar os dados pelo metodo post !-->

		<div class="form-group">
			<%= f.label :nome %>
			<%= f.text_field  :nome, class:"form-control" %>
		</div>
		<div class="form-group">
			<%= f.label :descricao %>
			<%= f.text_area :descricao,class:"form-control", rows: 4 %>
		</div>

		<div class="form-group">
			<%= f.label :departamento %>
			<%= f.collection_select :departamento_id, @departamentos, :id, :nome, {}, class: "form-control"  %>
		</div>

		
	<div class="form-inline">	
		<div class="form-group">
			<%= f.label :quantidade %>
			<%= f.number_field :quantidade ,step: 1,class:"form-control"%>
		</div>

		<div class="form-group">
			<%= f.label :preço %>
			<%= f.number_field :preco,class:"form-control" %>

		</div>
		<%= f.submit texto_que_muda, class: "btn btn-primary" %>
	</div>
		
	<% end -%>

app/views/produtos/_produto.html.erb
    <tr>
        <td><%= produto.nome %></%></td>
        <td><%= produto.descricao %></%></td>
        <td><%= produto.preco %></%></td>
        <td><%= button_to "Remover", produto,
                                    method: :delete,
                                    class: "btn btn-danger",
                                    data: { confirm: "Tem certeza que deseja remover #{produto.nome}?" }  %></td>
        <td><%= link_to "Alterar" , edit_produto_path(produto), class: "btn btn-default" %></td>
    </tr>

app/views/produtos/busca.html.erb
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Descrição</th>
            <th>Preço</th>
        </tr>
    </thead>
    <tbody>
        <%= render @produtos%>
    </tbody>
</table>

app/views/produtos/buscar.html.erb
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Descrição</th>
            <th>Preço</th>

        </tr>
    </thead>
    <tbody>
        <%= render @produtos %>
    </tbody>
</table>

app/views/produtos/create.html.erb
<!DOCTYPE html>

	<meta charset="utf-8">
	<title>
		
	</title>
</head>
	Criado!! <br>


 <th><%= link_to "Novo Produto", new_produto_url %></th><br>
<tr><%= link_to "Página Inicial",root_url  %></tr><br>

app/views/produtos/edit.html.erb
<%= render partial: 'forms', locals: { texto_que_muda: 'Atualizar o Produto'}  %>

app/views/produtos/index.html.erb
<!-- Aviso quando o produto é criado !-->
<% if flash[:notice]%>
	<div class = "alert alert-success" role = "alert"> <%= flash[:notice]%> </div>
<% end %>
<!-- Aviso quando o produto é excluido !-->
<% if flash[:notice1]%>
	<div class = "alert alert-danger" role = "alert"> <%= flash[:notice1]%> </div>
<% end %>

<!DOCTYPE html>

	<meta charset="utf-8">
	<title></title>
</head>
<body>
<table class="table table-striped"> 
	<thead>
		<tr>
			<th>Nome</th>
			<th>Descrição</th>
			<th>Preço</th>
		</tr>
	</thead>
	<tbody>
		<%= render @produtos_por_nome %>
	</tbody>
</table>

<table class="table table-striped"> 
	<thead>
		<tr>
			<th>Nome</th>
			<th>Descrição</th>
			<th>Preço</th>
		</tr>
	</thead>
	<tbody>
		<%= render @produtos_por_preco %>
	</tbody>

</table>

<%= link_to "Criar novo produto", new_produto_path %>

app/views/produtos/new.html.erb
<%= render partial: "forms", locals: {texto_que_muda: 'Criar o Produto'}  %>